/* COQ — Inicialización de la página de Conjugación */
(function(){
  function initTabs(){const tabButtons=[...document.querySelectorAll('.tab')];tabButtons.forEach(btn=>btn.addEventListener('click',()=>{tabButtons.forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.remove('active'));btn.classList.add('active');document.querySelector('#tab-'+btn.dataset.tab)?.classList.add('active')}))}
  function updateLookupStatus(){const input=document.getElementById('lookupVerb'),status=document.getElementById('lookupStatus'),tense=document.getElementById('lookupTense');if(!input||!status)return;const value=input.value.trim();if(!value){status.className='lookup-status empty';status.textContent='Escribe el infinitivo de un verbo francés.';status.hidden=false;return}const hasResult=document.getElementById('lookupResult')||document.querySelector('.verb-card');if(!hasResult){status.className='lookup-status empty';status.textContent=tense&&tense.value?'Escribe el verbo (en infinitivo) que quieras consultar. No estás limitado a una lista.':'Ahora selecciona un tiempo verbal.';status.hidden=false}}
  function initLookupStatus(){document.addEventListener('input',e=>{if(e.target&&e.target.id==='lookupVerb')updateLookupStatus()});document.addEventListener('change',e=>{if(e.target&&(e.target.id==='lookupVerb'||e.target.id==='lookupTense'))setTimeout(updateLookupStatus,30)})}
  function initPracticeShortcut(){document.addEventListener('click',function(e){const button=e.target.closest('#practiceThisVerb');if(!button)return;const verbInput=document.getElementById('lookupVerb'),practiceTab=document.querySelector('.tab[data-tab="practice"]'),practicePanel=document.getElementById('tab-practice'),practiceInput=document.getElementById('practiceVerb');if(practiceInput&&verbInput){practiceInput.value=verbInput.value.trim();practiceInput.dispatchEvent(new Event('input',{bubbles:true}));practiceInput.dispatchEvent(new Event('change',{bubbles:true}))}if(practiceTab)practiceTab.click();else if(practicePanel){document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.remove('active'));practicePanel.classList.add('active')}setTimeout(()=>{const panel=document.getElementById('tab-practice');if(panel)panel.scrollIntoView({behavior:'smooth',block:'start'})},50)})}
  function initPracticeSummary(){const validate=document.getElementById('validateAnswer'),input=document.getElementById('answerInput'),progress=document.getElementById('practiceProgressText'),modal=document.getElementById('resultModal');if(!validate||!input||!progress||!modal)return;const rows=new Map();let currentNumber=0,currentAttempts=0;
    function readQuestion(){const text=progress.textContent||'',m=text.match(/Question\s+(\d+)\s*\/\s*20/i);currentNumber=m?Number(m[1]):0;currentAttempts=0}
    function questionData(){return{number:currentNumber,verb:(document.getElementById('questionVerb')?.textContent||'').split(' · ')[0].trim(),tense:(document.getElementById('questionVerb')?.textContent||'').split(' · ').slice(1).join(' · ').trim(),subject:document.getElementById('questionSubject')?.textContent||''}}
    function extractCorrectAnswer(){const feedback=document.getElementById('practiceFeedback');if(!feedback)return'';const strong=feedback.querySelector('strong');if(strong)return strong.textContent.replace(/^Réponse correcte\s*:\s*/i,'').trim();const text=feedback.textContent||'',m=text.match(/Réponse correcte\s*:\s*(.+?)(?:\s+Escribe|$)/i);return m?m[1].trim():''}
    function recordAfterValidation(){const number=currentNumber;if(!number)return;const data=questionData(),value=input.value.trim(),cls=input.className||'';let row=rows.get(number);if(!row){row={...data,attempts:[],finalAnswer:'',correctAnswer:'',outcome:'correct-first'};rows.set(number,row)}
      if(value)row.attempts.push(value);
      if(cls.includes('error-first')){currentAttempts=1;row.outcome='error-first';return}
      if(cls.includes('error-second')){currentAttempts=2;row.outcome='incorrect-twice';row.correctAnswer=extractCorrectAnswer();return}
      if(cls.includes('success')){if(currentAttempts===0){row.outcome='correct-first';row.correctAnswer=value;row.finalAnswer=value}else if(currentAttempts===1){row.outcome='correct-after-first-error';row.correctAnswer=value;row.finalAnswer=value}else{row.outcome='incorrect-twice';row.finalAnswer=value;if(!row.correctAnswer)row.correctAnswer=value}if(number===20)setTimeout(renderSummary,750)}}
    function renderSummary(){const ordered=[...rows.values()].sort((a,b)=>a.number-b.number);if(ordered.length<20)return;const correct=ordered.filter(r=>r.outcome!=='incorrect-twice').length,errors=20-correct,score=ordered.reduce((sum,r)=>sum+(r.outcome==='correct-first'?1:r.outcome==='correct-after-first-error'?.5:0),0),note=Number.isInteger(score)?String(score):score.toFixed(1);const finalCorrect=document.getElementById('finalCorrect'),finalWrong=document.getElementById('finalWrong'),finalScore=document.getElementById('finalScore');if(finalCorrect)finalCorrect.textContent=String(correct);if(finalWrong)finalWrong.textContent=String(errors);if(finalScore)finalScore.textContent=`${note} / 20`;const tbody=document.getElementById('resultRows');if(tbody){tbody.innerHTML='';ordered.forEach(r=>{const tr=document.createElement('tr'),isWrong=r.outcome==='incorrect-twice',isFirstError=r.outcome==='correct-after-first-error',result=isWrong?'Corrigé avec aide':isFirstError?'Corrigé sans aide':'Correct',values=[r.number,r.verb,r.subject,r.tense,(r.attempts&&r.attempts.length?r.attempts.join(' → '):'—'),r.correctAnswer||'—',result];values.forEach((value,i)=>{const td=document.createElement('td');td.textContent=value;if(i===0)td.setAttribute('data-label','#');if(i===1)td.setAttribute('data-label','Verbe');if(i===2)td.setAttribute('data-label','Sujet');if(i===3)td.setAttribute('data-label','Temps');if(i===4)td.setAttribute('data-label','Ta réponse');if(i===5)td.setAttribute('data-label','Réponse correcte');if(i===6)td.setAttribute('data-label','Résultat');if(i===4){td.style.fontWeight='800';td.style.color=isWrong?'var(--red)':isFirstError?'var(--orange)':'var(--green)'}if(i===5){td.style.fontWeight='700';td.style.color='var(--green)'}if(i===6){td.style.fontWeight='800';td.style.color=isWrong?'var(--red)':isFirstError?'var(--orange)':'var(--green)'}tr.appendChild(td)});tbody.appendChild(tr)})}modal.classList.add('open');modal.setAttribute('aria-hidden','false');modal.style.display='flex'}
    function closeSummary(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');modal.style.display='none'}
    validate.addEventListener('click',()=>{if(!currentNumber)readQuestion();setTimeout(recordAfterValidation,30)});input.addEventListener('keydown',e=>{if(e.key==='Enter'){if(!currentNumber)readQuestion();setTimeout(recordAfterValidation,30)}});const observer=new MutationObserver(()=>{const text=progress.textContent||'',m=text.match(/Question\s+(\d+)\s*\/\s*20/i),n=m?Number(m[1]):0;if(n&&n!==currentNumber){currentNumber=n;currentAttempts=0}});observer.observe(progress,{childList:true,characterData:true,subtree:true});document.getElementById('reviewDone')?.addEventListener('click',closeSummary);modal.addEventListener('click',e=>{if(e.target===modal)closeSummary()})}
  function init(){initTabs();window.COQ_CONJ_LOOKUP.init();initLookupStatus();initPracticeShortcut();initPracticeSummary()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init()
})();
