/* COQ — Motor de conjugación data-driven. */
(function(){
  const P=window.COQ_CONJ_PRONOUNS,C=window.COQ_CONJ_COMPOUND,A=window.COQ_CONJ_AGREEMENT,S=P.subjectSets;
  const record=v=>window.COQ_CONJ_DATA_MODEL?.get?.(v)||null;
  const baseKey=v=>record(v)?.baseVerbId||v;
  function subjectIndex(subject,tense){const b=P.baseSubject(subject)||String(subject||'').trim().toLowerCase();if(tense==='impératif présent')return ({tu:0,nous:1,vous:2})[b]??null;return ({je:0,tu:1,il:2,elle:2,on:2,nous:3,vous:4,ils:5,elles:5})[b]??null;}
  function simpleForm(verb,tense,subject){const r=record(baseKey(verb)),rows=r?.formes?.[tense];if(!Array.isArray(rows))return null;const i=subjectIndex(subject,tense);return i==null||i>=rows.length?null:String(rows[i]??'').trim()||null;}
  function participle(v){return record(baseKey(v))?.participePasse||null;}
  function compoundForm(verb,tense,subject,construction){const r=record(verb);if(!r||!C?.isCompound?.(tense))return null;const info=P.subjectInfo(subject),pr=window.COQ_CONSTRUCTION_RESOLVER?.isPronominal(r,construction),aux=window.COQ_AUXILIARY_RESOLVER?.resolve(r,window.COQ_CONSTRUCTION_RESOLVER);if(!aux)return null;const af=simpleForm(aux,C.auxiliaryTense(tense),info.base),pp=participle(verb);if(!af||!pp)return null;let agreed=pp;if(A){if(pr){const rule=window.COQ_PRONOMINAL_RULES?.[baseKey(verb)];agreed=rule?.accord==='sujet'&&A.applySubjectAgreement?A.applySubjectAgreement(pp,{gender:info.gender,number:info.number}):A.stripAgreementMarkers?.(pp)||pp;}else if(aux==='être'&&A.applySubjectAgreement)agreed=A.applySubjectAgreement(pp,{gender:info.gender,number:info.number});else agreed=A.stripAgreementMarkers?.(pp)||pp;}if(pr){const pron=P.pronounFor(info.base),contracted=P.contractPronoun(pron,af);return (contracted.endsWith("'")?contracted+af:contracted+' '+af)+' '+agreed;}return af+' '+agreed;}
  function conjugate(verb,tense,subject,construction){const r=record(verb);if(!r)return null;const c=construction||((window.COQ_CONSTRUCTION_RESOLVER?.isPronominal(r))?'pronomiale':'non-pronomiale');if(C?.isCompound?.(tense))return compoundForm(verb,tense,subject,c);let f=simpleForm(baseKey(verb),tense,subject);if(f==null)return null;if(window.COQ_CONSTRUCTION_RESOLVER?.isPronominal(r,c)){if(tense==='impératif présent'){const p=P.imperativePronounFor?.(subject);return p?f+'-'+p:f;}f=P.apply(subject,f);}return f;}
  function rowsFor(verb,tense){const r=record(verb);if(!r)return [];const c=window.COQ_CONSTRUCTION_RESOLVER?.isPronominal(r)?'pronomiale':'non-pronomiale';if(C?.isCompound?.(tense)){const ss=tense==='subjonctif passé'?S.subjonctifPractice:S.practice;return ss.map(s=>[s,conjugate(verb,tense,P.baseSubject(s),c)]).filter(x=>x[1]!=null);}const ss=tense==='impératif présent'?S.imperative:tense==='subjonctif présent'?S.subjonctifSimpleFallback:S.simpleFallback;return ss.map(s=>{const raw=String(s).split('/').map(x=>x.trim())[0],f=conjugate(verb,tense,raw,c);return f!=null?[s,f]:null;}).filter(Boolean);}
  function rowsForLookup(verb,tense){return rowsFor(verb,tense);}
  function rowsForConstruction(verb,tense,construction){const r=record(verb);if(!r)return [];if(C?.isCompound?.(tense)){const ss=tense==='subjonctif passé'?S.subjonctifPractice:S.practice;return ss.map(s=>[s,conjugate(verb,tense,P.baseSubject(s),construction)]).filter(x=>x[1]!=null);}const ss=tense==='impératif présent'?S.imperative:tense==='subjonctif présent'?S.subjonctifConstructionFallback:S.simpleConstructionFallback;return ss.map(s=>{const raw=String(s).split('/').map(x=>x.trim())[0],f=conjugate(verb,tense,raw,construction);return f!=null?[s,f]:null;}).filter(Boolean);}
  function canGenerate(verb,tense){const r=record(verb);return !!r&&(C?.isCompound?.(tense)?!!window.COQ_AUXILIARY_RESOLVER?.resolve?.(r,window.COQ_CONSTRUCTION_RESOLVER):!!r.formes?.[tense]);}
  window.COQ_CONJ_ENGINE={conjugate,rowsFor,rowsForLookup,rowsForConstruction,canGenerate,subjectInfo:P.subjectInfo};
})();