/* COQ — Consulta de conjugaciones.
 * Responsabilidad: resolver la consulta, pedir las formas al motor y presentar la tabla.
 */
(function(){
  const U=window.COQ_CONJ_UTILS,conjugations=U.conjugations,resolver=window.COQ_PATTERN_RESOLVER,engine=window.COQ_CONJ_ENGINE,C=window.COQ_CONJ_COMPOUND;
  const SUBJECT_GROUPS={'il/elle/on':['il','elle','on'],'ils/elles':['ils','elles']},VOWELS=/^[aeiouàâäéèêëîïôöùûüÿœæ]/i;
  const record=v=>((resolver&&typeof resolver.resolveRecord==='function')?resolver.resolveRecord(v):null)||conjugations[v]||null;
  const meta=v=>record(v)||{},verbExists=verb=>!!record(verb),isCompound=tense=>!!C?.isCompound?.(tense);
  function counterpart(verb){const m=meta(verb);if(m.pronominal&&m.verbeBase&&record(m.verbeBase))return m.verbeBase;if(!m.pronominal&&m.formePronominale?.infinitif&&record(m.formePronominale.infinitif))return m.formePronominale.infinitif;if(!m.pronominal&&m.verbeBase&&record('se '+m.verbeBase))return 'se '+m.verbeBase;return null;}
  function toggleLabel(verb){return meta(verb).pronominal?'Voir sa forme non pronominale':'Voir sa forme pronominale';}
  function rowsForTense(verb,tense){return engine?.rowsForLookup?engine.rowsForLookup(verb,tense):((conjugations[verb]||{})[tense]||[]);}
  function normalizeSubject(value){return String(value||'').trim().toLowerCase().replace(/\s+/g,' ');}
  function stripMetadata(value){return String(value||'').replace(/\s*\([^)]*\)\s*/g,'').trim();}
  function baseSubject(value){return stripMetadata(value).replace(/^que\s+/i,'').replace(/^qu['’]/i,'').trim().toLowerCase();}
  function elideJe(label,form){const subject=normalizeSubject(label),value=String(form||'').trim();if(subject==='je'&&VOWELS.test(value))return "j'";if(subject==='que je'&&VOWELS.test(value))return "que j'";return label;}
  function addSubjonctifPrefix(label,form){const raw=String(label||'').trim(),base=baseSubject(raw),prefix={je:'que je',tu:'que tu',il:"qu'il",elle:"qu'elle",on:"qu'on",nous:'que nous',vous:'que vous',ils:"qu'ils",elles:"qu'elles"}[base];if(!prefix)return raw;if(/^que\s|^qu['’]/i.test(raw))return elideJe(raw,form);return elideJe(prefix,form);}
  function displaySubject(label,form,tense){const raw=String(label||'').trim(),base=normalizeSubject(stripMetadata(raw)),group=SUBJECT_GROUPS[base];if(group)return group.map(member=>tense==='subjonctif présent'?addSubjonctifPrefix(member,form):elideJe(member,form));return [tense==='subjonctif présent'?addSubjonctifPrefix(raw,form):elideJe(raw,form)];}
  function speechForm(form){return stripMetadata(form).replace(/\s+/g,' ').trim();}
  function normalizedRows(rows,tense){const output=[];(rows||[]).forEach(row=>{const form=String(row?.[1]??'').trim();if(!form)return;displaySubject(row?.[0],form,tense).forEach(subject=>output.push([subject,form]));});const verb=U.normalizeVerb(document.querySelector('#lookupVerb')?.value),pattern=resolver&&typeof resolver.resolvePattern==='function'?resolver.resolvePattern(verb):null;if(C?.isSimple?.(tense)&&pattern==='yer'){const merge=(subjects,label)=>{const matches=output.filter(row=>subjects.includes(row[0]));if(matches.length!==subjects.length||new Set(matches.map(row=>row[1])).size!==1)return;const first=output.indexOf(matches[0]);output.splice(first,matches.length,[label,matches[0][1]]);};merge(['il','elle','on'],'il/elle/on');merge(['ils','elles'],'ils/elles');}return output;}
  function addFormAudioButtons(table){const speak=window.Coqaudio&&typeof window.Coqaudio.speak==='function'?window.Coqaudio.speak:null;if(!speak)return;table.querySelectorAll('tbody tr').forEach(row=>{const cells=row.querySelectorAll('td');if(cells.length<2||cells[1].querySelector('[data-speak-form]'))return;const form=cells[1].textContent.trim(),spoken=speechForm(form);if(!spoken)return;const button=document.createElement('button');button.type='button';button.className='btn tiny secondary';button.dataset.speakForm=spoken;button.setAttribute('aria-label','Écouter la forme « '+spoken+' »');button.textContent='🔊';button.style.marginLeft='8px';button.addEventListener('click',()=>speak(spoken));cells[1].appendChild(button);});}
  function imperativeDecoration(rows){return rows.map(([subject,form])=>[subject==='tu'||subject==='nous'||subject==='vous'?subject+'*':subject,form]);}
  function renderRowsTable(tense,rows){let displayRows=normalizedRows(rows,tense);if(tense==='impératif présent')displayRows=imperativeDecoration(displayRows);let html='<div class="tense-block"><div class="tense-head"><h3>'+U.escapeHtml(tense)+'</h3><button class="btn tiny secondary" type="button" data-speak-tense="'+U.escapeHtml(tense)+'">🔊</button></div><table class="tense-table"><tbody>';displayRows.forEach(row=>{html+='<tr><td>'+U.escapeHtml(row[0])+'</td><td>'+U.escapeHtml(row[1])+'</td></tr>';});if(tense==='impératif présent')html+='<tr><td colspan="2">* En el imperativo los sujetos desaparecen. No se pronuncian, ni se escriben.</td></tr>';return html+'</tbody></table></div>';}
  function renderConjugation(verb){const result=document.querySelector('#conjResult');if(!result)return;result.classList.remove('hidden');const data=meta(verb).formes||conjugations[verb]||{},selectedTense=document.querySelector('#lookupTense')?.value||'',other=counterpart(verb);let html='<div class="card verb-summary" style="background:var(--soft-blue);border-color:#CBEAF4"><span class="tag">Conjugaison</span><div class="conj-result-head"><div><h2 style="margin-top:10px">'+U.escapeHtml(verb)+'</h2><p class="muted">'+(meta(verb).pronominal?'Forme pronominale':'Forme non pronominale')+'</p></div><div class="conj-actions">';if(other)html+='<button class="btn secondary" type="button" id="togglePronominal" data-target-verb="'+U.escapeHtml(other)+'">'+toggleLabel(verb)+'</button>';html+='<button class="btn secondary" type="button" id="speakVerb" aria-label="Escuchar el verbo">🔊 Escuchar el verbo</button><button class="btn tiny secondary" type="button" id="practiceThisVerb">Practicar este verbo</button></div></div></div>';if(selectedTense){const orderIndex=t=>{const i=(C?.displayOrder||[]).indexOf(t);return i===-1?9999:i;};let timesToShow=[];if(selectedTense==='Todos los tiempos'){timesToShow=(C?.displayOrder||[]).map(t=>[t,data[t]||[]]);Object.keys(data).filter(t=>!(C?.displayOrder||[]).includes(t)).forEach(t=>timesToShow.push([t,data[t]]));}else if(Object.prototype.hasOwnProperty.call(data,selectedTense)||engine?.canGenerate?.(verb,selectedTense))timesToShow=[[selectedTense,data[selectedTense]||[]]];timesToShow.sort((a,b)=>orderIndex(a[0])-orderIndex(b[0]));const generated=timesToShow.map(([tense])=>[tense,rowsForTense(verb,tense)]).filter(([,rows])=>rows?.length);html+='<div class="conj-toolbar"><span class="muted">'+(selectedTense==='Todos los tiempos'?'Todos los tiempos':'Tiempo seleccionado')+'</span></div>';if(!generated.length)html+='<div class="callout">Todavía no hay una conjugación disponible para <strong>'+U.escapeHtml(verb)+'</strong> en el tiempo «'+U.escapeHtml(selectedTense)+'».</div>';else{html+='<div class="conj-times" id="conjTimes">';generated.forEach(([tense,rows])=>{html+=renderRowsTable(tense,rows);});html+='</div>';}}else html+='<div class="callout">Selecciona un tiempo verbal para mostrar la conjugación.</div>';result.innerHTML=html;bindResultControls(verb);}
  function bindResultControls(verb){const speak=window.Coqaudio&&window.Coqaudio.speak?window.Coqaudio.speak:function(){};addFormAudioButtons(document.querySelector('#conjResult'));document.querySelector('#speakVerb')?.addEventListener('click',()=>speak(verb));document.querySelector('#togglePronominal')?.addEventListener('click',e=>{const target=e.currentTarget.dataset.targetVerb;document.querySelector('#lookupVerb').value=target;renderConjugation(target);setLookupMessage((document.querySelector('#lookupTense')?.value==='Todos los tiempos'?'Conjugación de todos los tiempos verbales cargada para «':'Conjugación cargada para «')+target+'».','form-message info');});document.querySelectorAll('[data-speak-tense]').forEach(button=>button.addEventListener('click',()=>{const tense=button.dataset.speakTense,rows=rowsForTense(verb,tense),spoken=[],seen=new Set();rows.forEach(row=>{const subject=stripMetadata(row[0]).trim(),form=speechForm(row[1]);if(!form)return;if(isCompound(tense)&&seen.has(subject))return;seen.add(subject);spoken.push((subject+' '+form).trim());});speak(spoken.join('. '));}));}
  function setLookupMessage(message,kind){const msg=document.querySelector('#lookupMessage');if(msg){msg.className=kind||'';msg.textContent=message||'';}}
  function hideResult(){document.querySelector('#conjResult')?.classList.add('hidden');}
  function lookup(){const input=document.querySelector('#lookupVerb'),tenseSelect=document.querySelector('#lookupTense'),v=U.normalizeVerb(input?.value);if(!v||!verbExists(v)||!tenseSelect?.value){setLookupMessage('','');hideResult();return;}const tense=tenseSelect.value;setLookupMessage(tense==='Todos los tiempos'?'Conjugación de todos los tiempos verbales cargada para «'+v+'».':'Conjugación del «'+tense+'» cargada para «'+v+'».','form-message info');renderConjugation(v);}
  function init(){document.querySelector('#lookupTense')?.addEventListener('change',lookup);document.querySelector('#lookupVerb')?.addEventListener('change',lookup);document.querySelector('#lookupVerb')?.addEventListener('keydown',e=>{if(e.key==='Enter')lookup();});document.querySelectorAll('.suggestion').forEach(button=>button.addEventListener('click',()=>{document.querySelector('#lookupVerb').value=button.dataset.verb;lookup();}));const verbInput=document.getElementById('lookupVerb');if(verbInput){let timer=null;verbInput.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{const v=U.normalizeVerb(verbInput.value);if(v&&verbExists(v)&&document.querySelector('#lookupTense')?.value)lookup();else{hideResult();setLookupMessage('','');}},300);});}}
  window.COQ_CONJ_LOOKUP={lookup,renderConjugation,init,normalizedRows};
})();
