const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
const context=vm.createContext({window:{},document:{querySelector:()=>null,getElementById:()=>null,querySelectorAll:()=>[]},console,Set,Map,Object,Array,Math,String,Number,Boolean,RegExp,JSON});
vm.runInContext(fs.readFileSync(path.join(root,'js/conjugaison/pronouns.js'),'utf8'),context,{filename:'js/conjugaison/pronouns.js'});
const P=context.window.COQ_CONJ_PRONOUNS;
const assert=(condition,message)=>{if(!condition)throw new Error(message);};
const expect=(actual,expected,label)=>assert(actual===expected,`${label}: esperado «${expected}», obtenido «${actual}»`);
assert(P,'El modelo canónico de sujetos debe estar disponible.');
assert(Object.isFrozen(P.subjectVariants),'Las variantes de sujeto deben ser inmutables.');
assert(Object.isFrozen(P.subjectSets),'Los conjuntos canónicos de sujetos deben ser inmutables.');
['lookupCompound','practice','subjonctifPractice','simpleFallback','subjonctifSimpleFallback','subjonctifConstructionFallback','simpleConstructionFallback','imperative'].forEach(key=>assert(Object.isFrozen(P.subjectSets[key]),`El conjunto ${key} debe ser inmutable.`));
expect(P.baseSubject('que je'),'je','que je debe normalizar a je.');
expect(P.baseSubject('vous (féminin singulier)'),'vous','Los contextos de género/número deben conservar el sujeto base.');
expect(P.subjectForMode('je','normal','ai'),"j'",'La elisión de je debe ser canónica.');
expect(P.subjectForMode('que je','subjonctif','aie'),"que j'",'La elisión de que je debe ser canónica.');
expect(P.subjectForMode('vous (féminin singulier)','subjonctif','sois'),'que vous (féminin singulier)','El subjuntivo debe conservar el contexto del sujeto.');
expect(P.subjectForMode('elle','normal','est'),'elle','Los sujetos sin elisión deben permanecer intactos.');
expect(P.subjectSets.lookupCompound.join(','),'je,tu,il,elle,on,nous,vous,ils,elles','Lookup compuesto debe conservar sus nueve sujetos.');
expect(P.subjectSets.practice.join(','),'je,tu,il,elle,on,nous,vous,ils,elles','Practice debe conservar sus nueve sujetos.');
expect(P.subjectSets.subjonctifPractice.join(','),"que je,que tu,qu'il,qu'elle,qu'on,que nous,que vous,qu'ils,qu'elles",'Practice de subjuntivo debe conservar sus nueve sujetos.');
expect(P.subjectSets.simpleFallback.join(','),'je,tu,il/elle/on,nous,vous,ils/elles','Fallback simple debe conservar los grupos pedagógicos.');
expect(P.subjectSets.subjonctifSimpleFallback.join(','),"que je,que tu,qu'il/elle/on,que nous,que vous,qu'ils/elles",'Fallback simple de subjuntivo debe conservar los grupos pedagógicos.');
expect(P.subjectSets.subjonctifConstructionFallback.join(','),"que je,que tu,qu'il,que nous,que vous,qu'ils",'Fallback de construcción de subjuntivo debe conservar sus sujetos.');
expect(P.subjectSets.simpleConstructionFallback.join(','),'je,tu,il,elle,on,nous,vous,ils,elles','Fallback de construcción simple debe conservar sus nueve sujetos.');
expect(P.subjectSets.imperative.join(','),'tu,nous,vous','El imperativo debe conservar sus tres sujetos.');
const practice=fs.readFileSync(path.join(root,'js/conjugaison/practice.js'),'utf8');
const lookup=fs.readFileSync(path.join(root,'js/conjugaison/lookup.js'),'utf8');
const engine=fs.readFileSync(path.join(root,'js/conjugaison/engine.js'),'utf8');
assert(!/const SUBJECT_VARIANTS\s*=/.test(practice),'Practice no debe declarar una copia local de subjectVariants.');
assert(!/function PSubject\s*\(/.test(practice),'Practice no debe declarar una copia local de baseSubject.');
assert(!/const prefix=\{/.test(practice),'Practice no debe declarar un mapa local de sujetos de subjuntivo.');
assert(!/function baseSubject\s*\(/.test(lookup),'Lookup no debe declarar una copia local de baseSubject.');
assert(!/function addSubjonctifPrefix\s*\(/.test(lookup),'Lookup no debe declarar una copia local del prefijo de subjuntivo.');
assert(!/function elideJe\s*\(/.test(lookup),'Lookup no debe declarar una copia local de la elisión de sujetos.');
['LOOKUP_COMPOUND_SUBJECTS','PRACTICE_SUBJECTS','SUBJONCTIF_PRACTICE_SUBJECTS','SIMPLE_FALLBACK_SUBJECTS','SUBJONCTIF_SIMPLE_FALLBACK_SUBJECTS','SUBJONCTIF_CONSTRUCTION_FALLBACK_SUBJECTS','IMPERATIVE_SUBJECTS'].forEach(name=>assert(!new RegExp(`const ${name}\\s*=`).test(engine),`Engine no debe declarar el conjunto local ${name}.`));
assert(/const [^;]*S=P\.subjectSets/.test(engine),'Engine debe consumir los conjuntos canónicos de P.subjectSets.');
console.log('Conjugaison subject model: OK');
