const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
const context=vm.createContext({window:{},document:{querySelector:()=>null,getElementById:()=>null,querySelectorAll:()=>[]},console,Set,Map,Object,Array,Math,String,Number,Boolean,RegExp,JSON});
const files=['data/verbs/verbs.js','data/verbs/family-catalog.js','data/verbs/patterns.js','data/verbs/constructions.js','data/verbs/tense-rules.js','js/conjugaison/utils.js','js/conjugaison/pronouns.js','js/conjugaison/compound-tenses.js','js/conjugaison/agreement.js','js/conjugaison/pattern-registry.js','js/conjugaison/engine.js','js/conjugaison/lookup.js'];
files.forEach(file=>vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context,{filename:file}));
const w=context.window,engine=w.COQ_CONJ_ENGINE,lookup=w.COQ_CONJ_LOOKUP;
const assert=(condition,message)=>{if(!condition)throw new Error(message);};
const expect=(actual,expected,label)=>assert(actual===expected,`${label}: esperado «${expected}», obtenido «${actual}»`);
assert(w.COQ_VERBS['parler'],'Los datos base deben seguir intactos tras cargar el catálogo.');
assert(!Object.prototype.hasOwnProperty.call(w.COQ_VERBS,'sortir'),'El catálogo familiar no debe mutar COQ_VERBS.');
assert(w.COQ_VERB_REGISTRY['partir'],'El registro unificado debe conservar verbos provenientes de catálogos familiares.');
assert(w.COQ_VERB_REGISTRY['partir'].pattern==='partir-type','El registro familiar de partir debe conservar su patrón.');
assert(Object.isFrozen(w.COQ_VERB_FAMILY_CATALOG),'El catálogo familiar debe ser inmutable.');
assert(Object.isFrozen(w.COQ_VERB_REGISTRY),'El registro unificado debe ser inmutable.');
expect(engine.conjugate('parler',"présent de l'indicatif",'je'),'parle','parler presente');
expect(engine.conjugate('manger',"présent de l'indicatif",'nous'),'mangeons','manger nous');
expect(engine.conjugate('commencer',"présent de l'indicatif",'nous'),'commençons','commencer nous');
expect(engine.conjugate('appeler',"présent de l'indicatif",'je'),'appelle','appeler je');
expect(engine.conjugate('acheter',"présent de l'indicatif",'je'),'achète','acheter je');
expect(engine.conjugate('nettoyer',"présent de l'indicatif",'je'),'nettoie','nettoyer je');
expect(engine.conjugate('prendre',"présent de l'indicatif",'ils'),'prennent','prendre ils');
expect(engine.conjugate('partir','passé composé','je (masculin singulier)'),'suis parti','partir passé composé');
expect(engine.conjugate('partir','plus-que-parfait','je (féminin singulier)'),'étais partie','partir plus-que-parfait');
expect(engine.conjugate('être','passé composé','je (masculin singulier)'),'ai été','être passé composé');
expect(engine.conjugate('faire','conditionnel passé','nous (féminin pluriel)'),'aurions fait','faire conditionnel passé');
expect(engine.conjugate('se lever','passé composé','vous (féminin singulier)','pronominale'),'vous êtes levée','se lever passé composé');
expect(engine.conjugate('se lever','plus-que-parfait','tu (masculin singulier)','pronominale'),"t'étais levé",'se lever plus-que-parfait');
expect(engine.conjugate('se parler','passé composé','ils','pronominale'),'se sont parlé','se parler sans accord');
expect(engine.conjugate('venir','futur antérieur','elles'),'seront venues','venir futur antérieur');
expect(w.COQ_VERB_REGISTRY['venir'].auxiliaire,'être','venir doit conservar son auxiliaire être dans el registro normalizado');
const practiceRows=engine.rowsFor('se lever','passé composé');
assert(practiceRows.length===9,'La pratique doit partir de 9 sujets de base avant expansión de variantes.');
assert(practiceRows.every(row=>!/[()]/.test(row[0])),'Les lignes de práctica ne doivent pas contenir variantes de género/número ya expandidas.');
const lookupRows=lookup.normalizedRows(engine.rowsForLookup('se lever','passé composé'),'passé composé','se lever');
assert(lookupRows.length===12,'La consulta pronominal con être debe mostrar 12 posibilidades pedagógicas de sujeto.');
expect(lookupRows[0][0],'je','La tabla pronominal debe usar je.');
expect(lookupRows[0][1],'me suis levé(e)','je debe conservar la notación genérica.');
expect(lookupRows[1][0],'tu','La tabla pronominal debe usar tu.');
expect(lookupRows[1][1],"t'es levé(e)",'tu debe conservar la notación genérica.');
expect(lookupRows[2][0],'il','La tabla pronominal debe separar il.');
expect(lookupRows[2][1],"s'est levé",'il debe usar el masculino singular.');
expect(lookupRows[3][0],'elle','La tabla pronominal debe separar elle.');
expect(lookupRows[3][1],"s'est levée",'elle debe usar el femenino singular.');
expect(lookupRows[4][0],'on','La tabla pronominal debe separar on.');
expect(lookupRows[4][1],"s'est levé(e)(s)",'on debe conservar las posibilidades de género y número.');
expect(lookupRows[5][0],'nous','La tabla pronominal debe usar nous.');
expect(lookupRows[5][1],'nous sommes levé(e)s','nous debe conservar la notación plural.');
expect(lookupRows[6][0],'vous (masculin singulier)','La tabla pronominal debe distinguir vous masculino singular.');
expect(lookupRows[6][1],'vous êtes levé','vous masculino singular debe ser levé.');
expect(lookupRows[7][0],'vous (féminin singulier)','La tabla pronominal debe distinguir vous femenino singular.');
expect(lookupRows[7][1],'vous êtes levée','vous femenino singular debe ser levée.');
expect(lookupRows[8][0],'vous (masculin pluriel)','La tabla pronominal debe distinguir vous masculino plural.');
expect(lookupRows[8][1],'vous êtes levés','vous masculino plural debe ser levés.');
expect(lookupRows[9][0],'vous (féminin pluriel)','La tabla pronominal debe distinguir vous femenino plural.');
expect(lookupRows[9][1],'vous êtes levées','vous femenino plural debe ser levées.');
expect(lookupRows[10][0],'ils','La tabla pronominal debe separar ils.');
expect(lookupRows[10][1],'se sont levés','ils debe usar el masculino plural.');
expect(lookupRows[11][0],'elles','La tabla pronominal debe separar elles.');
expect(lookupRows[11][1],'se sont levées','elles debe usar el femenino plural.');
const simpleLookup=lookup.normalizedRows(engine.rowsForLookup('parler',"présent de l'indicatif"),"présent de l'indicatif",'parler');
assert(simpleLookup.length===9,'La tabla simple debe mostrar los 9 sujetos separados.');
expect(simpleLookup[2][0],'il','La tabla simple debe separar il.');
expect(simpleLookup[3][0],'elle','La tabla simple debe separar elle.');
expect(simpleLookup[4][0],'on','La tabla simple debe separar on.');
expect(simpleLookup[7][0],'ils','La tabla simple debe separar ils.');
expect(simpleLookup[8][0],'elles','La tabla simple debe separar elles.');
const subjLookup=lookup.normalizedRows(engine.rowsForLookup('parler','subjonctif présent'),'subjonctif présent','parler');
assert(subjLookup.length===9,'La tabla de subjonctif présent debe mostrar los 9 sujetos separados.');
expect(subjLookup[2][0],"qu'il",'La tabla de subjonctif debe separar qu’il.');
expect(subjLookup[3][0],"qu'elle",'La tabla de subjonctif debe separar qu’elle.');
expect(subjLookup[4][0],"qu'on",'La tabla de subjonctif debe separar qu’on.');
const avoirCompound=lookup.normalizedRows(engine.rowsForLookup('avoir','passé composé'),'passé composé','avoir');
assert(avoirCompound.length===6,'Los tiempos compuestos con avoir deben conservar 6 sujetos y ninguna concordancia.');
const etreCompound=lookup.normalizedRows(engine.rowsForLookup('venir','passé composé'),'passé composé','venir');
assert(etreCompound.length===12,'Los tiempos compuestos con être deben mostrar 12 posibilidades por concordancia.');
expect(etreCompound[0][0],'je','La tabla être debe usar je.');
expect(etreCompound[0][1],'suis venu(e)','je debe conservar la notación genérica.');
expect(etreCompound[2][0],'il','La tabla être debe separar il.');
expect(etreCompound[2][1],'est venu','il debe usar masculino singular.');
expect(etreCompound[3][0],'elle','La tabla être debe separar elle.');
expect(etreCompound[3][1],'est venue','elle debe usar femenino singular.');
expect(etreCompound[4][0],'on','La tabla être debe separar on.');
expect(etreCompound[4][1],'est venu(e)(s)','on debe conservar las posibilidades.');
expect(etreCompound[6][0],'vous (masculin singulier)','La tabla être debe distinguir vous masculino singular.');
expect(etreCompound[6][1],'êtes venu','vous masculino singular debe ser venu.');
expect(etreCompound[7][1],'êtes venue','vous femenino singular debe ser venue.');
expect(etreCompound[8][1],'êtes venus','vous masculino plural debe ser venus.');
expect(etreCompound[9][1],'êtes venues','vous femenino plural debe ser venues.');
expect(etreCompound[10][0],'ils','La tabla être debe separar ils.');
expect(etreCompound[10][1],'sont venus','ils debe usar masculino plural.');
expect(etreCompound[11][0],'elles','La tabla être debe separar elles.');
expect(etreCompound[11][1],'sont venues','elles debe usar femenino plural.');
const subjonctifPasse=lookup.normalizedRows(engine.rowsForLookup('venir','subjonctif passé'),'subjonctif passé','venir');
assert(subjonctifPasse.length===12,'El subjonctif passé con être debe mostrar 12 posibilidades por concordancia.');
expect(subjonctifPasse[2][0],"qu'il",'El subjonctif passé debe separar qu’il.');
expect(subjonctifPasse[3][0],"qu'elle",'El subjonctif passé debe separar qu’elle.');
expect(subjonctifPasse[4][0],"qu'on",'El subjonctif passé debe separar qu’on.');
console.log('Conjugaison regression OK — sujetos separados y concordancia de être verificada.');
