const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
const context=vm.createContext({window:{},document:{querySelector:()=>null,getElementById:()=>null,querySelectorAll:()=>[]},console,Set,Map,Object,Array,Math,String,Number,Boolean,RegExp,JSON});
vm.runInContext(fs.readFileSync(path.join(root,'js/conjugaison/pronouns.js'),'utf8'),context,{filename:'js/conjugaison/pronouns.js'});
const P=context.window.COQ_CONJ_PRONOUNS;
const assert=(condition,message)=>{if(!condition)throw new Error(message);};
const expect=(actual,expected,label)=>assert(actual===expected,`${label}: esperado «${expected}», obtenido «${actual}»`);
assert(P,'El modelo canónico de sujetos debe estar disponible.');
assert(Object.isFrozen(P.subjectVariants),'Las variantes de sujeto deben ser inmutables.');
expect(P.baseSubject('que je'),'je','que je debe normalizar a je.');
expect(P.baseSubject('vous (féminin singulier)'),'vous','Los contextos de género/número deben conservar el sujeto base.');
expect(P.subjectForMode('je','normal','ai'),"j'",'La elisión de je debe ser canónica.');
expect(P.subjectForMode('que je','subjonctif','aie'),"que j'",'La elisión de que je debe ser canónica.');
expect(P.subjectForMode('vous (féminin singulier)','subjonctif','sois'),'que vous (féminin singulier)','El subjuntivo debe conservar el contexto del sujeto.');
expect(P.subjectForMode('elle','normal','est'),'elle','Los sujetos sin elisión deben permanecer intactos.');
const practice=fs.readFileSync(path.join(root,'js/conjugaison/practice.js'),'utf8');
const lookup=fs.readFileSync(path.join(root,'js/conjugaison/lookup.js'),'utf8');
assert(!/const SUBJECT_VARIANTS\s*=/.test(practice),'Practice no debe declarar una copia local de subjectVariants.');
assert(!/function PSubject\s*\(/.test(practice),'Practice no debe declarar una copia local de baseSubject.');
assert(!/const prefix=\{/.test(practice),'Practice no debe declarar un mapa local de sujetos de subjuntivo.');
assert(!/function baseSubject\s*\(/.test(lookup),'Lookup no debe declarar una copia local de baseSubject.');
assert(!/function addSubjonctifPrefix\s*\(/.test(lookup),'Lookup no debe declarar una copia local del prefijo de subjuntivo.');
assert(!/function elideJe\s*\(/.test(lookup),'Lookup no debe declarar una copia local de la elisión de sujetos.');
console.log('Conjugaison subject model: OK');
