const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
const context=vm.createContext({window:{},console,Object,Array,Set,Map,String,Number,Boolean,RegExp,JSON});
vm.runInContext(fs.readFileSync(path.join(root,'data/verbs/constructions.js'),'utf8'),context,{filename:'data/verbs/constructions.js'});
vm.runInContext(fs.readFileSync(path.join(root,'data/verbs/auxiliaries.js'),'utf8'),context,{filename:'data/verbs/auxiliaries.js'});
const w=context.window;
const assert=(condition,message)=>{if(!condition)throw new Error(message);};
const resolver=w.COQ_AUXILIARY_RESOLVER;
assert(resolver,'El resolver de auxiliares debe existir.');
assert(typeof resolver.resolve==='function','El resolver debe exponer resolve.');
assert(typeof resolver.matches==='function','El resolver debe exponer matches.');
const pronominal={pronominal:true,auxiliaire:'avoir'};
const avoir={pronominal:false,auxiliaire:'avoir'};
const etre={pronominal:false,auxiliaire:'être'};
const compound=['passé composé','plus-que-parfait','conditionnel passé','futur antérieur','subjonctif passé'];
assert(resolver.resolve(pronominal,w.COQ_CONSTRUCTION_RESOLVER)==='être','Un verbe pronominal doit résoudre vers ÊTRE.');
assert(resolver.resolve(avoir,w.COQ_CONSTRUCTION_RESOLVER)==='avoir','Un verbe AVOIR doit conserver son auxiliaire déclaré.');
assert(resolver.resolve(etre,w.COQ_CONSTRUCTION_RESOLVER)==='être','Un verbe ÊTRE doit conserver son auxiliaire déclaré.');
assert(resolver.matches(avoir,'passé composé','avec-avoir',compound,w.COQ_CONSTRUCTION_RESOLVER),'Le filtre AVOIR doit accepter un verbe à AVOIR.');
assert(!resolver.matches(avoir,'passé composé','avec-etre',compound,w.COQ_CONSTRUCTION_RESOLVER),'Le filtre ÊTRE ne doit pas accepter un verbe à AVOIR.');
assert(resolver.matches(pronominal,'passé composé','avec-etre',compound,w.COQ_CONSTRUCTION_RESOLVER),'Le filtre ÊTRE doit accepter un pronominal.');
assert(resolver.matches(pronominal,'passé composé','avec-avoir-et-etre',compound,w.COQ_CONSTRUCTION_RESOLVER),'Le filtre combiné doit accepter un pronominal.');
const practice=fs.readFileSync(path.join(root,'js/conjugaison/practice.js'),'utf8');
const engine=fs.readFileSync(path.join(root,'js/conjugaison/engine.js'),'utf8');
assert(!/COQ_COMPOUND_CONSTRUCTION_FILTERS/.test(practice),'Practice no debe consumir el catálogo antiguo de filtros de auxiliares.');
assert(!/COQ_COMPOUND_CONSTRUCTION_FILTERS/.test(engine),'Engine no debe consumir el catálogo antiguo de filtros de auxiliares.');
console.log('✓ Auxiliary resolver ownership regression passed');
