const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
const context=vm.createContext({window:{},console,Object,Array,Set,Map,String,Number,Boolean,RegExp,JSON});
vm.runInContext(fs.readFileSync(path.join(root,'data/verbs/constructions.js'),'utf8'),context,{filename:'data/verbs/constructions.js'});
const w=context.window;
const assert=(condition,message)=>{if(!condition)throw new Error(message);};
const resolver=w.COQ_CONSTRUCTION_RESOLVER;
assert(resolver,'El resolver de construcciones debe existir.');
assert(typeof resolver.isPronominal==='function','El resolver debe exponer isPronominal.');
assert(typeof resolver.matchesConstruction==='function','El resolver debe exponer matchesConstruction.');
assert(typeof resolver.matchesAuxiliary==='undefined','La resolución de auxiliares no debe pertenecer al resolver de construcciones.');
const pronominal={pronominal:true};
const nonPronominal={pronominal:false,auxiliaire:'avoir'};
assert(resolver.isPronominal(pronominal),'Un verbo pronominal debe resolverse como pronominal.');
assert(!resolver.isPronominal(nonPronominal),'Un verbo no pronominal no debe resolverse como pronominal.');
assert(resolver.matchesConstruction(pronominal,'pronominale'),'El filtro pronominal debe coincidir.');
assert(resolver.matchesConstruction(nonPronominal,'non-pronominale'),'El filtro no pronominal debe coincidir.');
assert(!resolver.matchesConstruction(pronominal,'non-pronominale'),'Un pronominal no debe pasar el filtro no pronominal.');
const practice=fs.readFileSync(path.join(root,'js/conjugaison/practice.js'),'utf8');
const engine=fs.readFileSync(path.join(root,'js/conjugaison/engine.js'),'utf8');
assert(!/function matchesConstruction\s*\([^)]*\)\s*\{[^}]*m\.pronominal/.test(practice),'Practice no debe contener la regla local de construcción pronominal.');
assert(!/function matchesAuxiliary\s*\([^)]*\)\s*\{[^}]*m\.pronominal/.test(practice),'Practice no debe contener la regla local de auxiliar.');
assert(!/construction==='pronominale'\|\|r\.pronominal===true/.test(engine),'Engine no debe duplicar la regla histórica de resolución pronominal.');
console.log('✓ Construction resolver ownership regression passed');
