const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
const context=vm.createContext({window:{},document:{querySelector:()=>null,getElementById:()=>null,querySelectorAll:()=>[]},console,Object,Array,Set,Map,String,Number,Boolean,RegExp,JSON});
['data/verbs/verbs.js','data/verbs/verbs-extended.js','data/verbs/family-catalog.js','data/verbs/category-catalog.js','data/verbs/canonical-model.js','data/verbs/patterns.js'].forEach(file=>vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context,{filename:file}));
const w=context.window;
const assert=(condition,message)=>{if(!condition)throw new Error(message);};
assert(Array.isArray(w.COQ_VERB_CATEGORY_CATALOG),'El catálogo de categorías debe existir.');
assert(w.COQ_CATEGORY_RESOLVER&&typeof w.COQ_CATEGORY_RESOLVER.categoryOptions==='function','El resolver de categorías debe exponer categoryOptions.');
assert(typeof w.COQ_CATEGORY_RESOLVER.matchesCategory==='function','El resolver de categorías debe exponer matchesCategory.');
assert(typeof w.COQ_PATTERN_RESOLVER.categoryOptions==='undefined','El resolver de patterns no debe exponer la API de categorías.');
assert(typeof w.COQ_PATTERN_RESOLVER.matchesGroup==='undefined','El resolver de patterns no debe exponer reglas de categorías con nomenclatura histórica.');
const options=w.COQ_CATEGORY_RESOLVER.categoryOptions();
assert(options.length===w.COQ_VERB_CATEGORY_CATALOG.length,'categoryOptions debe reflejar exactamente el catálogo canónico.');
assert(options.some(category=>category.id==='er-eler'),'categoryOptions debe conservar las categorías pedagógicas existentes.');
assert(w.COQ_CATEGORY_RESOLVER.matchesCategory('appeler','er-eler'),'appeler debe resolverse dentro de la categoría er-eler.');
assert(!w.COQ_CATEGORY_RESOLVER.matchesCategory('appeler','er-eter'),'appeler no debe pertenecer a la categoría er-eter.');
assert(w.COQ_CATEGORY_RESOLVER.matchesCategory('prendre','groupe-3'),'prendre debe pertenecer al tercer grupo.');
console.log('✓ Category resolver ownership regression passed');
