const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
const context=vm.createContext({window:{},document:{querySelector:()=>null,getElementById:()=>null,querySelectorAll:()=>[]},console,Object,Array,Set,Map,String,Number,Boolean,RegExp,JSON});
['data/verbs/verbs.js','data/verbs/verbs-extended.js','data/verbs/family-catalog.js','data/verbs/canonical-model.js','data/verbs/patterns.js'].forEach(file=>vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context,{filename:file}));
const w=context.window;
const assert=(condition,message)=>{if(!condition)throw new Error(message);};
assert(w.COQ_FAMILY_RESOLVER&&typeof w.COQ_FAMILY_RESOLVER.resolve==='function','El resolver de familias debe existir y exponer resolve.');
assert(typeof w.COQ_FAMILY_RESOLVER.options==='function','El resolver de familias debe exponer options.');
assert(typeof w.COQ_PATTERN_RESOLVER.familyOptions==='undefined','El resolver de patterns no debe exponer familyOptions.');
assert(typeof w.COQ_PATTERN_RESOLVER.resolveFamily==='undefined','El resolver de patterns no debe resolver familias.');
assert(typeof w.COQ_CONJ_DATA_MODEL.familyIndex==='undefined','El modelo canónico no debe duplicar el índice de familias.');
assert(typeof w.COQ_CONJ_DATA_MODEL.getFamilyVerbs==='undefined','El modelo canónico no debe exponer resolución de familias.');
assert(typeof w.COQ_CONJ_DATA_MODEL.get('parler')?.legacyVerbeBase==='undefined','El modelo canónico no debe exponer legacyVerbeBase.');
assert(typeof w.COQ_CONJ_DATA_MODEL.get('se lever')?.legacyVerbeBase==='undefined','Las relaciones con el verbo base deben exponerse mediante baseVerbId, no legacyVerbeBase.');
assert(w.COQ_CONJ_DATA_MODEL.get('se lever')?.baseVerbId==='lever','se lever debe conservar su verbo base mediante baseVerbId.');
const families=w.COQ_VERB_FAMILIES||{};
const options=w.COQ_FAMILY_RESOLVER.options();
assert(options.length===Object.keys(families).length,'options debe reflejar exactamente el catálogo de familias.');
const familyById=new Map(Object.entries(families));
options.forEach(option=>{
  assert(option&&typeof option.id==='string','Cada opción de familia debe declarar un id.');
  assert(familyById.has(option.id),`Family resolver option references unknown family ${option.id}`);
  const family=familyById.get(option.id);
  assert(option.patternId===family.patternId,`Family resolver pattern mismatch for ${option.id}`);
  assert(Number(option.groupe)===Number(family.groupe),`Family resolver groupe mismatch for ${option.id}`);
  assert(Array.isArray(option.verbs),'Cada opción de familia debe conservar su lista de verbos.');
  assert(option.verbs.length===family.verbs.length,`Family resolver verb count mismatch for ${option.id}`);
  family.verbs.forEach(verb=>assert(option.verbs.includes(verb),`Family resolver lost verb ${verb} from ${option.id}`));
});
assert(new Set(options.map(option=>option.id)).size===options.length,'El resolver de familias no debe duplicar opciones.');
assert(w.COQ_FAMILY_RESOLVER.resolve('parler')?.id==='er-regular','parler debe resolverse en er-regular.');
assert(w.COQ_FAMILY_RESOLVER.resolve('APPELER')?.id==='er-eler-double','La resolución familiar debe normalizar mayúsculas.');
assert(w.COQ_FAMILY_RESOLVER.resolve('verbe-inexistant')===null,'Un verbo desconocido no debe resolver una familia.');
assert(w.COQ_PATTERN_RESOLVER.resolvePattern('parler')==='regular-er','La resolución de pattern debe seguir funcionando después de separar ownership.');
console.log('✓ Family resolver ownership regression passed');
