const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
const context=vm.createContext({window:{},document:{querySelector:()=>null,getElementById:()=>null,querySelectorAll:()=>[]},console,Set,Map,Object,Array,Math,String,Number,Boolean,RegExp,JSON});
const files=['data/verbs/verbs.js','data/verbs/family-catalog.js','data/verbs/patterns.js','data/verbs/constructions.js','data/verbs/tense-rules.js','js/conjugaison/utils.js','js/conjugaison/pronouns.js','js/conjugaison/compound-tenses.js','js/conjugaison/agreement.js','js/conjugaison/pattern-registry.js','js/conjugaison/engine.js','js/conjugaison/lookup.js'];
files.forEach(file=>vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context,{filename:file}));
const w=context.window,engine=w.COQ_CONJ_ENGINE,lookup=w.COQ_CONJ_LOOKUP;
const assert=(condition,message)=>{if(!condition)throw new Error(message);};
const expect=(actual,expected,label)=>assert(actual===expected,`${label}: esperado «${expected}», obtenido «${actual}»`);
assert(w.COQ_VERBS['parler'],'Los datos base deben seguir intactos tras cargar el catálogo.');
assert(!Object.prototype.hasOwnProperty.call(w.COQ_VERBS,'sortir'),'El catálogo familiar no debe mutar COQ_VERBS.');
assert(w.COQ_VERB_REGISTRY['partir'],'El registro unificado debe conservar verbos provenientes de catálogos familiares.');
assert(w.COQ_VERB_REGISTRY['partir'].pattern==='partir-type','El registro familiar de partir debe conservar su patrón.');
assert(Object.isFrozen(w.COQ_VERB_FAMILY_CATALOG),'El catálogo familiar debe ser inmutable.');
assert(Object.isFrozen(w.COQ_VERB_REGISTRY),'El registro unificado debe ser inmutable.');
expect(engine.conjugate('parler',"présent de l'indicatif",'je'),'parle','parler presente');
expect(engine.conjugate('manger',"présent de l'indicatif",'nous'),'mangeons','manger nous');
expect(engine.conjugate('commencer',"présent de l'indicatif",'nous'),'commençons','commencer nous');
expect(engine.conjugate('appeler',"présent de l'indicatif",'je'),'appelle','appeler je');
expect(engine.conjugate('acheter',"présent de l'indicatif",'je'),'achète','acheter je');
expect(engine.conjugate('nettoyer',"présent de l'indicatif",'je'),'nettoie','nettoyer je');
expect(engine.conjugate('prendre',"présent de l'indicatif",'ils'),'prennent','prendre ils');
expect(engine.conjugate('partir','passé composé','je (masculin singulier)'),'suis parti','partir passé composé');
expect(engine.conjugate('partir','plus-que-parfait','je (féminin singulier)'),'étais partie','partir plus-que-parfait');
expect(engine.conjugate('être','passé composé','je (masculin singulier)'),'ai été','être passé composé');
expect(engine.conjugate('faire','conditionnel passé','nous (féminin pluriel)'),'aurions fait','faire conditionnel passé');
expect(engine.conjugate('se lever','passé composé','vous (féminin singulier)','pronominale'),'vous êtes levée','se lever passé composé');
expect(engine.conjugate('se lever','plus-que-parfait','tu (masculin singulier)','pronominale'),"t'étais levé",'se lever plus-que-parfait');
expect(engine.conjugate('se parler','passé composé','ils','pronominale'),'se sont parlé','se parler sans accord');
expect(engine.conjugate('venir','futur antérieur','elles'),'seront venues','venir futur antérieur');
expect(w.COQ_VERB_REGISTRY['venir'].auxiliaire,'être','venir doit conservar son auxiliaire être dans el registro normalizado');
const practiceRows=engine.rowsFor('se lever','passé composé');
assert(practiceRows.length===9,'La pratique doit partir de 9 sujets de base avant expansion des variantes.');
assert(practiceRows.every(row=>!/[()]/.test(row[0])),'Les lignes de práctica ne doivent pas contenir variantes de género/número ya expandidas.');
const lookupRows=engine.rowsForLookup('se lever','passé composé');
assert(lookupRows.length===6,'La consulta pronominal debe conservar 6 filas pedagógicas agrupadas.');
expect(lookupRows[0][0],'je','La tabla pronominal debe usar el sujeto je.');
expect(lookupRows[2][0],'il/elle/on','La tabla pronominal debe agrupar il/elle/on.');
expect(lookupRows[5][0],'ils/elles','La tabla pronominal debe agrupar ils/elles.');
const simpleLookup=lookup.normalizedRows(engine.rowsForLookup('parler',"présent de l'indicatif"),"présent de l'indicatif",'parler');
assert(simpleLookup.length===6,'La tabla simple debe conservar las 6 filas pedagógicas agrupadas.');
expect(simpleLookup[2][0],'il/elle/on','La tabla simple debe agrupar il/elle/on.');
expect(simpleLookup[5][0],'ils/elles','La tabla simple debe agrupar ils/elles.');
const subjLookup=lookup.normalizedRows(engine.rowsForLookup('parler','subjonctif présent'),'subjonctif présent','parler');
assert(subjLookup.length===6,'La tabla de subjonctif présent debe conservar las 6 filas pedagógicas.');
expect(subjLookup[2][0],"qu'il/elle/on",'La tabla de subjonctif debe agrupar qu’il/elle/on.');
const avoirCompound=lookup.normalizedRows(engine.rowsForLookup('avoir','passé composé'),'passé composé','avoir');
assert(avoirCompound.length===6,'Los tiempos compuestos con avoir no deben expandirse artificialmente por género.');
const etreCompound=lookup.normalizedRows(engine.rowsForLookup('venir','passé composé'),'passé composé','venir');
assert(etreCompound.length===6,'Los tiempos compuestos con être deben conservar 6 filas pedagógicas agrupadas.');
expect(etreCompound[0][0],'je','La tabla être debe usar el sujeto je.');
expect(etreCompound[0][1],'suis venu(e)','La tabla être debe indicar el acuerdo femenino de je.');
expect(etreCompound[2][1],'est venu(e)(s)','La tabla être debe indicar las posibilidades de il/elle/on.');
expect(etreCompound[3][1],'sommes venu(e)s','La tabla être debe indicar el acuerdo plural de nous.');
expect(etreCompound[4][1],'êtes venu(e)(s)','La tabla être debe indicar las posibilidades de vous.');
expect(etreCompound[5][1],'sont venu(e)s','La tabla être debe indicar el acuerdo de ils/elles.');
const subjonctifPasse=lookup.normalizedRows(engine.rowsForLookup('venir','subjonctif passé'),'subjonctif passé','venir');
assert(subjonctifPasse.length===6,'El subjonctif passé debe conservar 6 filas pedagógicas agrupadas.');
expect(subjonctifPasse[2][0],"qu'il/elle/on",'El subjonctif passé debe agrupar qu’il/elle/on.');
console.log('Conjugaison regression OK — 42 assertions.');
