const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
const context=vm.createContext({window:{},document:{querySelector:()=>null,getElementById:()=>null,querySelectorAll:()=>[]},console,Set,Map,Object,Array,Math,String,Number,Boolean,RegExp,JSON});
const files=['data/verbs/verbs.js','data/verbs/family-catalog.js','data/verbs/patterns.js','data/verbs/constructions.js','data/verbs/tense-rules.js','js/conjugaison/utils.js','js/conjugaison/pronouns.js','js/conjugaison/compound-tenses.js','js/conjugaison/agreement.js','js/conjugaison/pattern-registry.js','js/conjugaison/engine.js','js/conjugaison/lookup.js'];
files.forEach(file=>vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context,{filename:file}));
const w=context.window;
if(!w.COQ_CONJ_PRACTICE_TESTING)throw new Error('La API de prueba de práctica no está disponible.');
const select=w.COQ_CONJ_PRACTICE_TESTING.selectPracticeQuestions;
const assert=(condition,message)=>{if(!condition)throw new Error(message);};
const key=q=>[q.verb,q.tense,String(q.subject).trim().toLowerCase(),q.displayAnswer||q.answer].join('|');
const makePool=()=>{
  const pool=[];
  const subjects=['je','tu','il','elle','on','nous','vous','ils','elles'];
  const tenses=['présent de l’indicatif','imparfait','futur simple','conditionnel présent'];
  const verbs=['parler','finir','prendre','venir','faire','avoir'];
  for(const verb of verbs)for(const tense of tenses)for(const subject of subjects)pool.push({verb,tense,subject,answer:`${verb}-${tense}-${subject}`,displayAnswer:`${verb}-${tense}-${subject}`});
  return pool;
};
const result=select(makePool(),20);
assert(result.length===20,'La selección debe producir exactamente 20 preguntas cuando el pool lo permite.');
assert(new Set(result.map(key)).size===20,'La selección no debe contener preguntas duplicadas.');
for(let i=1;i<result.length;i++)assert(result[i-1].subject.toLowerCase()!==result[i].subject.toLowerCase(),'No debe repetir inmediatamente el mismo sujeto.');
const subjectCounts=new Map();
result.forEach(q=>subjectCounts.set(q.subject,(subjectCounts.get(q.subject)||0)+1));
assert(Math.max(...subjectCounts.values())-Math.min(...subjectCounts.values())<=1,'La distribución de sujetos debe mantenerse equilibrada en un pool amplio.');
const small=makePool().slice(0,20);
const smallResult=select(small,20);
assert(smallResult.length===20,'Un pool de exactamente 20 preguntas debe conservar las 20.');
assert(new Set(smallResult.map(key)).size===20,'Un pool de exactamente 20 preguntas no debe introducir duplicados.');
const duplicatePool=[...makePool().slice(0,10),...makePool().slice(0,10)];
const deduped=select(duplicatePool,20);
assert(deduped.length===10,'Las preguntas idénticas deben deduplicarse antes de seleccionar.');
console.log('Conjugaison practice distribution OK — 20 preguntas, sin duplicados y sujetos equilibrados.');
