const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
const context=vm.createContext({window:{},console,Set,Map,Object,Array,Math,String,Number,Boolean,RegExp,JSON});
const files=['data/verbs/verbs.js','data/verbs/family-catalog.js','data/verbs/patterns.js','data/verbs/constructions.js','data/verbs/tense-rules.js','js/conjugaison/utils.js','js/conjugaison/pronouns.js','js/conjugaison/compound-tenses.js','js/conjugaison/agreement.js','js/conjugaison/pattern-registry.js','js/conjugaison/engine.js'];
files.forEach(file=>vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context,{filename:file}));
const w=context.window,engine=w.COQ_CONJ_ENGINE;
const assert=(condition,message)=>{if(!condition)throw new Error(message);};
const expect=(actual,expected,label)=>assert(actual===expected,`${label}: esperado «${expected}», obtenido «${actual}»`);
assert(w.COQ_VERBS['parler'],'Los datos base deben seguir intactos tras cargar el catálogo.');
assert(!Object.prototype.hasOwnProperty.call(w.COQ_VERBS,'sortir'),'El catálogo familiar no debe mutar COQ_VERBS.');
assert(w.COQ_VERB_REGISTRY['partir'],'El registro unificado debe conservar verbos provenientes de catálogos familiares.');
assert(w.COQ_VERB_REGISTRY['partir'].pattern==='partir-type','El registro familiar de partir debe conservar su patrón.');
assert(Object.isFrozen(w.COQ_VERB_FAMILY_CATALOG),'El catálogo familiar debe ser inmutable.');
assert(Object.isFrozen(w.COQ_VERB_REGISTRY),'El registro unificado debe ser inmutable.');
expect(engine.conjugate('parler',"présent de l'indicatif",'je'),'parle','parler presente');
expect(engine.conjugate('manger',"présent de l'indicatif",'nous'),'mangeons','manger nous');
expect(engine.conjugate('commencer',"présent de l'indicatif",'nous'),'commençons','commencer nous');
expect(engine.conjugate('appeler',"présent de l'indicatif",'je'),'appelle','appeler je');
expect(engine.conjugate('acheter',"présent de l'indicatif",'je'),'achète','acheter je');
expect(engine.conjugate('nettoyer',"présent de l'indicatif",'je'),'nettoie','nettoyer je');
expect(engine.conjugate('prendre',"présent de l'indicatif",'ils'),'prennent','prendre ils');
expect(engine.conjugate('partir','passé composé','je (masculin singulier)'),'suis parti','partir passé composé');
expect(engine.conjugate('partir','plus-que-parfait','je (féminin singulier)'),'étais partie','partir plus-que-parfait');
expect(engine.conjugate('être','passé composé','je (masculin singulier)'),'ai été','être passé composé');
expect(engine.conjugate('faire','conditionnel passé','nous (féminin pluriel)'),'aurions fait','faire conditionnel passé');
expect(engine.conjugate('se lever','passé composé','vous (féminin singulier)','pronominale'),'vous êtes levée','se lever passé composé');
expect(engine.conjugate('se lever','plus-que-parfait','tu (masculin singulier)','pronominale'),"t'étais levé",'se lever plus-que-parfait');
expect(engine.conjugate('se parler','passé composé','ils','pronominale'),'se sont parlé','se parler sans accord');
expect(engine.conjugate('venir','futur antérieur','elles'),'seront venues','venir futur antérieur');
console.log('Conjugaison regression OK — 21 assertions.');
