const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
const context=vm.createContext({window:{},console,Object,Array,Set,Map,String,Number,Boolean,RegExp,JSON});
vm.runInContext(fs.readFileSync(path.join(root,'data/verbs/constructions.js'),'utf8'),context,{filename:'data/verbs/constructions.js'});
vm.runInContext(fs.readFileSync(path.join(root,'js/conjugaison/agreement.js'),'utf8'),context,{filename:'js/conjugaison/agreement.js'});
const w=context.window;
const assert=(condition,message)=>{if(!condition)throw new Error(message);};
const expect=(actual,expected,message)=>assert(actual===expected,`${message}: esperado «${expected}», obtenido «${actual}»`);
const agreement=w.COQ_CONJ_AGREEMENT;
assert(agreement&&typeof agreement.formatLookupCompoundForm==='function','El formateador de Consulta debe existir.');
expect(w.COQ_PRONOMINAL_RULES['parler']?.fonctionDeSe,'COI','se parler debe declarar un COI.');
expect(w.COQ_PRONOMINAL_RULES['parler']?.accord,'aucun','se parler no debe concordar.');
expect(w.COQ_PRONOMINAL_RULES['téléphoner']?.fonctionDeSe,'COI','se téléphoner debe declarar un COI.');
expect(w.COQ_PRONOMINAL_RULES['téléphoner']?.accord,'aucun','se téléphoner no debe concordar.');
const parler={pronominal:true,construction:'pronomiale',auxiliaire:'être',participePasse:'parlé',baseVerbId:'parler'};
const telephoner={pronominal:true,construction:'pronomiale',auxiliaire:'être',participePasse:'téléphoné',baseVerbId:'téléphoner'};
const lever={pronominal:true,construction:'pronomiale',auxiliaire:'être',participePasse:'levé',baseVerbId:'lever'};
expect(agreement.formatLookupCompoundForm('me suis parlé','je',parler,'se parler'),'me suis parlé','Consulta de se parler no debe mostrar marca de concordancia');
expect(agreement.formatLookupCompoundForm('me suis téléphoné','je',telephoner,'se téléphoner'),'me suis téléphoné','Consulta de se téléphoner no debe mostrar marca de concordancia');
expect(agreement.formatLookupCompoundForm('me suis levé','je',lever,'se lever'),'me suis levé(e)','Consulta de se lever debe conservar la marca de concordancia');
console.log('✓ COI agreement regression passed');
